"""empty message

Revision ID: 36269b579d71
Revises: bc582f027133
Create Date: 2019-06-10 14:26:56.644459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36269b579d71'
down_revision = 'bc582f027133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('order', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'order')
    # ### end Alembic commands ###
